services:
  - type: web
    name: julia-bolt
    runtime: node
    plan: starter  # Change to 'standard' for production
    buildCommand: npm ci --include=dev && npm run build:render
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "18"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=4096"
      - key: PORT
        value: 10000
      - key: GITHUB_TOKEN
        sync: false
      - key: VITE_GITHUB_ACCESS_TOKEN
        sync: false
      - key: VITE_GITHUB_TOKEN_TYPE
        value: classic
      - key: VITE_LOG_LEVEL
        value: info
    # Auto-deploy from main branch
    branch: main
    # Health check endpoint
    healthCheckPath: /api/health
    # Build settings
    buildFilter:
      paths:
        - app/**
        - public/**
        - scripts/**
        - package.json
        - package-lock.json
        - vite.config.ts
        - tsconfig.json
        - vite-electron.config.ts
